language: generic
os:
  - linux
#  - osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-7
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then FC=gfortran-7 cmake .; fi
  - cmake --build .
script:
  - ctest
notifications:
email: false
after_success:
- bash <(curl -s https://codecov.io/bash)
