language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-7
before_script:
  - FC=gfortran-7 cmake .
  - cmake --build .
script:
  - ctest
notifications:
email: false
after_success:
- bash <(curl -s https://codecov.io/bash)
